### PR TITLE
Add NUOPC cap to the model to support external land component under UFS

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to add ESMF/NUOPC cap to the Noah MP model. The cap basically uses noahmpdrv.F90 which is provided by CCPP to drive the model. The current version of the model is tested with data model configurations and also side-by-side configuration with active atmosphere under UFS Weather model and new RTs are defined. This version of code also includes files for component testing through the GitHub action. In this case, the datm+lnd configuration (very similar to the RT test that is defined under UFS Weather Model) with is compiled outside of the UFS Weather Model and runs for one day.

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
This is ready for merge at the UFSWM level. Please review as needed and merge.

**Comment by BrianCurtis-NOAA** [comment]
@barlage Can you review please?

**Review by barlage — APPROVED** [review]
This PR supports the implementation of noahmp component model based on a snapshot of ccpp-physics version of the code. Eventually, when ccpp-physics submodules the NOAA-EMC fork of NCAR, this will need to be updated. I have some minor concerns about the storage of netcdf tiles that are not relevant for non-UFS applications of noahmp, but that hopefully can be dealt with later.

**Comment by uturuncoglu** [comment]
@barlage Could you also give me admin access to this repository once you merge the PR. So, I could make some minor modifications to activate testing with GitHub action. Once, we have working action, you could change the access privileges to the original version.

**Comment by barlage** [comment]
@uturuncoglu do you have a minute to talk about this? I'm having trouble merging to develop.

**Comment by uturuncoglu** [comment]
sure.

**Pull request merged**
