### PR TITLE
Update NoahMP model

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to bring fully coupled atmosphere-land configuration to UFS Weather Model. It also fix couple of issues related with the GitHub Action.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@uturuncoglu Who can review and approve this PR?

**Comment by uturuncoglu** [comment]
@barlage can do it.

**Review by barlage — APPROVED** [review]
Looks good and consistent with the land model updates for HR3. I like the addition of the output "density" (low, med, high).

**Comment by jkbk2004** [comment]
@uturuncoglu @barlage All tests  are done ate weather model. can you merge this pr? If you add jkbk2004 to this repo, I can handle merging.

**Comment by uturuncoglu** [comment]
@jkbk2004 done.

**Pull request merged**
