### PR TITLE
Update for consistency with ccpp-physics HR4 updates

### PR DESCRIPTION
**Pull request by barlage**
Update noahmp repository with @HelinWei-NOAA updates for [HR4 land updates ](https://github.com/ufs-community/ccpp-physics/pull/219)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@uturuncoglu can you review/approve this pr?

**Comment by yangfanglin** [comment]
@barlage @HelinWei-NOAA  are we starting to use NOAH-MP repo/fork for UFS applications ?  Will https://github.com/ufs-community/ccpp-physics/tree/ufs/dev/physics/SFC_Models/Land/Noahmp be removed from CCPP, then check out this fork as a submodule ?

**Comment by yangfanglin** [comment]
I guess this is used by  the component land model

**Comment by uturuncoglu** [comment]
@jkbk2004 okay. This is merged. I am assuming that all the land tests are passing.

**Pull request merged**
