### PR TITLE
Fix debug mode issue

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to fix couple of issues with the component land model. The fully coupled atm+lnd configuration (`control_p8_atmlnd`) was failing in debug mode. To fix the issue, the NOAHMP NUOPC cap is modified to read required fixed information from the sfc_data file. The more information can be seen in https://github.com/ufs-community/ufs-weather-model/issues/2189

### CODE REVIEW

**Comment by jkbk2004** [comment]
@barlage can you review this pr? we are going to schedule to commit this pr soon. Can you give me maintain level permission to this repo? So I can handle the PR processing.

**Comment by uturuncoglu** [comment]
@jkbk2004 I have just add you as a collaborator.

**Review by barlage — APPROVED** [review]

**Comment by zach1221** [comment]
@uturuncoglu Testing complete on WM PR#2191. Please merge this PR.

**Comment by uturuncoglu** [comment]
@zach1221 done.

**Pull request merged**
