### PR TITLE
Add 'rca' variable to noahmpdrv_run interface for CCPP/physics PR#205

### PR DESCRIPTION
**Pull request by grantfirl**
Needed for https://github.com/ufs-community/ufs-weather-model/pull/2264 and https://github.com/ufs-community/ccpp-physics/pull/205

Add `rca` variable to NUOPC cap for `noahmpdrv_run()`.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@uturuncoglu @barlage Could one of you please review this PR?

**Comment by barlage** [comment]
@DeniseWorthen I believe there is some additional testing being performed within [ccpp-physics](https://github.com/ufs-community/ccpp-physics/pull/205#issuecomment-2108690112) 

@grantfirl @uturuncoglu @drnimbusrain

**Comment by drnimbusrain** [comment]
Hi Mike and Denise,

Yes, I need to test further the rca output in the other PR by @grantfirl.

Patrick

**Comment by grantfirl** [comment]
@drnimbusrain @DeniseWorthen @barlage @uturuncoglu This has been updated to reflect the latest changes from @drnimbusrain. I believe that it is ready for final review at this point.

**Review by uturuncoglu — APPROVED** [review]
It looks good to me.

**Comment by barlage** [comment]
@grantfirl are the noahmpdrv updates in [ccpp-physics 205](https://github.com/ufs-community/ccpp-physics/pull/205) ready to go for this PR also?

**Comment by barlage** [comment]
@grantfirl sorry, I think I see the parameter limit changes now

**Comment by grantfirl** [comment]
> @grantfirl sorry, I think I see the parameter limit changes now

Yep, the changes here should be identical to https://github.com/ufs-community/ccpp-physics/pull/205

**Review by barlage — APPROVED** [review]

**Comment by jkbk2004** [comment]
Tests are done ok at https://github.com/ufs-community/ufs-weather-model/pull/2264. We can merge this pr.

**Pull request merged**
