### PR TITLE
Land surface upgrades for HR2

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to bring changes related to the new soil color dataset to the component model.

### CODE REVIEW

**Review by HelinWei-NOAA — APPROVED** [review]

**Comment by uturuncoglu** [comment]
@HelinWei-NOAA @barlage The build seems fine under action but run crashed due to missing `INPUT/C96.soil_color.tile*.nc` files which is expected. These files need to be push to the cloud once the PR is in.

**Comment by uturuncoglu** [comment]
@HelinWei-NOAA @barlage GitHub action test is passing now after syncing new soil color dataset with S3 bucket.

**Comment by FernandoAndrade-NOAA** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1777 Testing has been completed successfully, please go ahead and approve and begin the merge process, thank you.

**Comment by jkbk2004** [comment]
@uturuncoglu @BarbaraStunder-NOAA can you hold a bit? We need to check ccpp pr.

**Comment by jkbk2004** [comment]
There is a syncing issue on https://github.com/ufs-community/ccpp-physics/pull/78. We need to hold a bit.

**Comment by FernandoAndrade-NOAA** [comment]
Looks like ccpp #[78 ](https://github.com/ufs-community/ccpp-physics/pull/78)was a false alarm on the sync issue, please go ahead and continue.

**Comment by jkbk2004** [comment]
@uturuncoglu @barlage The issue on ccpp side was cleared. All sets now. Can you merge in this pr?

**Review by barlage — APPROVED** [review]

**Comment by jkbk2004** [comment]
@barlage thanks for merging the pr!

**Pull request merged**
